project:
  type: website

website:
  title: "Tampa Bay Weather"
  site-url: "https://jbradley28-design02.github.io/tampa-bay-weather"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exploration.qmd
        text: 10-Year History
      - href: records.qmd
        text: Records
      - text: Natural Disasters
        menu:
          - href: disasters.qmd
            text: "All Disasters Overview & Records"
          - href: disaster-hermine.qmd
            text: "Hurricane Hermine (2016) Telemetry"
          - href: disaster-irma.qmd
            text: "Hurricane Irma (2017) Telemetry"
          - href: disaster-michael.qmd
            text: "Hurricane Michael (2018) Telemetry"
          - href: disaster-ian.qmd
            text: "Hurricane Ian (2022) Telemetry"
          - href: disaster-freeze.qmd
            text: "Christmas Arctic Freeze (2022) Telemetry"
          - href: disaster-idalia.qmd
            text: "Hurricane Idalia (2023) Telemetry"
          - href: disaster-debby.qmd
            text: "Hurricane Debby (2024) Telemetry"
          - href: disaster-helene.qmd
            text: "Hurricane Helene (2024) Telemetry"
          - href: disaster-milton.qmd
            text: "Hurricane Milton (2024) Telemetry"
      - href: recent.qmd
        text: Recent Data
      - href: story.qmd
        text: Anatomy of a Storm
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - text: |
          <script src="live-weather.js"></script>
