project:
  type: website

website:
  title: "Tampa Bay Weather"
  site-url: "https://jbradley28-design02.github.io/tampa-bay-weather"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exploration.qmd
        text: Exploration
      - href: records.qmd
        text: Records
      - href: disasters.qmd
        text: Natural Disasters
      - href: story.qmd
        text: Story
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body:
      - text: |
          <script src="live-weather.js"></script>
